version: "3"

services:
  payload-service:
    container_name: payload-service
    image: "marsy/payload-service"
    restart: always
    ports:
      - 3004:8080

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:15.2
    container_name: database-payload
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-payload
    ports:
      - 3007:5432