version: "3"

services:
  rocket-hardware-mock-service:
    container_name: payload-hardware-mock-service
    image: "marsy/payload-hardware-mock-service"
    restart: always
    ports:
      - 3009:8080
