version: "3"

services:
  telemetry-service:
    container_name: telemetry-service
    image: "marsy/telemetry-service"
    restart: always
    ports:
      - 3003:8080
    environment:
      - POSTGRES_HOST=postgres:5432
    depends_on:
      - postgres

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:15.2
    container_name: database-telemetry
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-telemetry
    ports:
      - "3006:5432"

