version: "3"

services:
  rocket-hardware-mock-service:
    container_name: rocket-hardware-mock-service
    image: "marsy/rocket-hardware-mock-service"
    restart: always
    ports:
      - 3005:8080
